#ifndef SRC_ZCL_ZCL_CUSTOM_ATTR_H_
#define SRC_ZCL_ZCL_CUSTOM_ATTR_H_

//#define ZCL_TEMPERATURE_MEASUREMENT_ATTRID_SENSORS_READ_PERIOD          0xF000
//#define ZCL_TEMPERATURE_MEASUREMENT_ATTRID_TEMPERATURE_OFFSET           0xF001
//#define ZCL_TEMPERATURE_MEASUREMENT_ATTRID_TEMPERATURE_ONOFF            0xF002
//#define ZCL_TEMPERATURE_MEASUREMENT_ATTRID_TEMPERATURE_ONOFF_LOW        0xF003
//#define ZCL_TEMPERATURE_MEASUREMENT_ATTRID_TEMPERATURE_ONOFF_HIGH       0xF004
//#define ZCL_RELATIVE_HUMIDITY_MEASUREMENT_ATTRID_HUMIDITY_OFFSET        0xF005
//#define ZCL_RELATIVE_HUMIDITY_MEASUREMENT_ATTRID_HUMIDITY_ONOFF         0xF006
//#define ZCL_RELATIVE_HUMIDITY_MEASUREMENT_ATTRID_HUMIDITY_ONOFF_LOW     0xF007
//#define ZCL_RELATIVE_HUMIDITY_MEASUREMENT_ATTRID_HUMIDITY_ONOFF_HIGH    0xF008

#endif /* SRC_ZCL_ZCL_CUSTOM_ATTR_H_ */
